name: Fetch NYT EPUB

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6 AM
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Calibre installation
        uses: actions/cache@v4
        with:
          path: /usr/share/calibre
          key: calibre-${{ runner.os }}
          restore-keys: |
            calibre-

      - name: Install Calibre
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      - name: Fetch and Convert NY Times
        run: |
          TODAY=$(date '+%Y-%m-%d')
          ebook-convert ./nytimes.recipe ./nyt-${TODAY}.epub
          echo "Generated nyt-${TODAY}.epub"
          echo "artifact-name=nyt-${TODAY}" >> $GITHUB_ENV

      - name: Upload EPUB with Date-Stamped Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-name }}
          path: ./nyt-*.epub