name: Fetch NYT EPUB

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6 AM
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Calibre
        run: sudo apt-get update && sudo apt-get install -y calibre

      - name: Fetch and Convert NY Times
        run: |
          ebook-convert "NY Times.recipe" ./nyt.epub
          echo "Fetched and converted NYT to EPUB"

      - name: Upload to Release
        uses: actions/upload-artifact@v3
        with:
          name: NYT.epub
          path: ./nyt.epub