name: Fetch NYT EPUB

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6 AM UTC
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Calibre installation
        uses: actions/cache@v4
        with:
          path: /usr/share/calibre
          key: calibre-${{ runner.os }}
          restore-keys: |
            calibre-

      - name: Install Required Packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre imagemagick wget git

      - name: Set Date for File Naming
        id: date
        run: |
          export TZ="America/New_York"
          echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download NY Times Recipe
        run: |
          wget -O "nytimes.recipe" "https://raw.githubusercontent.com/kovidgoyal/calibre/refs/heads/master/recipes/nytimes.recipe"

      - name: Download High-Resolution Front Page PDF
        run: |
          export TZ="America/New_York"
          TODAY=$(date '+%Y/%m/%d')
          echo "Using date: $TODAY"
          wget -O "scan.pdf" "https://static01.nyt.com/images/${TODAY}/nytfrontpage/scan.pdf"

      - name: Convert PDF to High-Resolution JPG
        run: |
          # Convert the first page of the PDF to a high-quality JPG
          convert -density 300 "scan.pdf[0]" -quality 85 "cover.jpg"

      - name: Fetch and Convert NY Times to EPUB
        run: |
          TODAY=${{ env.DATE }}
          ebook-convert "./nytimes.recipe" "./nyt-${TODAY}.epub" --cover="cover.jpg"
          echo "Generated nyt-${TODAY}.epub"
          mkdir -p ./epubs/nyt
          mv "./nyt-${TODAY}.epub" "./epubs/nyt/nyt-${TODAY}.epub"

      - name: Commit and Push EPUB to Repository
        run: |
          TODAY=${{ env.DATE }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "./epubs/nyt/nyt-${TODAY}.epub"
          git commit -m "Add NYT EPUB for ${TODAY}"
          git push